modLoader="javafml"
loaderVersion="[35,)"
license="Not specified"

[[mods]]
modId="bubble_gum_simulator"
version="1.3.9b"
displayName="Bubble Gum Simulator"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Tech Norris"

[[dependencies.bubble_gum_simulator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




